server:
  shutdown: graceful

logging.level.com.airwallex: TRACE

grpc:
  server:
    enabled: false
  client:
    channels:
      book:
        host: localhost
        port: 8090
        tls:
          enabled: false
#        defaultLoadBalancingPolicy: round_robin

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
      show-details: ALWAYS
spring:
  application:
    name: book-web
#  zipkin:
#    baseUrl: http://zipkin:9411/

logging.pattern.level: trace_id=%mdc{trace_id} span_id=%mdc{span_id} trace_flags=%mdc{trace_flags} %5p
