server:
  shutdown: graceful

logging.level.com.airwallex: TRACE

grpc:
  server:
    enabled: false
  client:
    channels:
      book:
        host: localhost
        port: 8090
        tls:
          enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
      show-details: ALWAYS
spring:
  application:
    name: book-web
  zipkin:
    baseUrl: http://zipkin:9411/
