grpc:
  server:
    enable-server-reflection: true #for grpcurl
    connection-management:
      max-connection-age: 5m
#    health:
#      use-grpc-probe: true
logging.level.com.airwallex: TRACE

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
      group:
        liveness:
          include: livenessState,grpcServer
        readiness:
          include: readinessState,grpcServer
      show-details: ALWAYS
spring:
  application:
    name: book-service
  zipkin:
    baseUrl: http://zipkin:9411/
